version: '3'

services:
  backend:
    build:
      context: ../
      dockerfile: ./deployment/api/Dockerfile
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    container_name: streamlit-frontend
    ports:
      - "8501:8501"
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge